import { createClient } from '@supabase/supabase-js'
import { initAuthCreds, BufferJSON, proto } from '@whiskeysockets/baileys'
import ws from 'ws'

const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, {
  realtime: { transport: ws }
})

// ── Low-level row helpers (shared by everything below) ──────────────────────
// Centralised here so the session-import logic and the Baileys keystore
// always read/write rows the exact same way — no risk of the two drifting apart.

async function dbGet(key) {
  const { data } = await sb.from('wa_session').select('value').eq('key', key).single()
  return data ? JSON.parse(data.value, BufferJSON.reviver) : null
}

async function dbSet(key, value) {
  await sb.from('wa_session').upsert({ key, value: JSON.stringify(value, BufferJSON.replacer) })
}

async function dbDel(key) {
  await sb.from('wa_session').delete().eq('key', key)
}

// ── Session string import (Levanter-compatible) ──────────────────────────────
//
// A "session string" from Levanter (and most Baileys-family bots) is just the
// bot's Baileys `creds` object, JSON-stringified with Baileys' own BufferJSON
// replacer (so Buffers survive as {type:'Buffer',data:[...]}), then base64
// encoded, sometimes with a "BotName;;" or "BotName~" tag glued on the front
// so the receiving bot can sanity-check where it came from. This does NOT
// include the full signal keystore (that's regenerated/resynced over the
// connection) — just enough to prove the device is already linked.

function decodeSessionString(rawInput) {
  let s = rawInput.trim()

  // Railway / most host UIs will happily store a value with the quotes typed
  // literally if the user pasted `SESSION_ID="Levanter;;...."` — strip that.
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    s = s.slice(1, -1).trim()
  }

  // Strip a "BotName;;" or "BotName~" tag if present. Levanter uses ";;";
  // a few other MD bots (Subzero and friends) use "~". Only strip the FIRST
  // occurrence so a base64 payload that happens to contain these chars later
  // on is left untouched.
  if (s.includes(';;')) {
    s = s.slice(s.indexOf(';;') + 2).trim()
  } else if (s.includes('~')) {
    s = s.slice(s.indexOf('~') + 1).trim()
  }

  let decoded
  try {
    decoded = JSON.parse(Buffer.from(s, 'base64').toString('utf8'), BufferJSON.reviver)
  } catch (e) {
    throw new Error(`not valid base64/JSON after stripping prefix (${e.message})`)
  }

  // Two shapes are common in the wild: { creds: {...}, "pre-key-1": {...}, ... }
  // (nested, with extra keystore entries) or the creds object directly (flat).
  const credsObj = decoded && typeof decoded === 'object' && decoded.creds
    ? decoded.creds
    : decoded

  // Sanity check BEFORE we let anything touch the database. noiseKey and
  // signedIdentityKey are generated by initAuthCreds() and present on every
  // real Baileys creds object — if they're missing this almost certainly
  // isn't a Baileys session string (wrong bot's format, truncated paste, etc).
  if (!credsObj || typeof credsObj !== 'object' || !credsObj.noiseKey || !credsObj.signedIdentityKey) {
    throw new Error('decoded value does not look like Baileys creds (missing noiseKey/signedIdentityKey)')
  }

  return { credsObj, extras: decoded && decoded.creds ? decoded : null }
}

async function importSessionString() {
  const SESSION_ID = process.env.SESSION_ID
  if (!SESSION_ID) return

  // Never clobber a session the bot has already established for itself —
  // SESSION_ID is a one-time bootstrap, not something to re-apply on every deploy.
  const existing = await dbGet('creds')
  if (existing) return

  try {
    const { credsObj, extras } = decodeSessionString(SESSION_ID)

    await dbSet('creds', credsObj)

    if (extras) {
      for (const [key, value] of Object.entries(extras)) {
        if (key === 'creds') continue
        await dbSet(key, value)
      }
    }

    console.log('🦩 SESSION_ID imported successfully — pairing code will be skipped on this boot')
  } catch (e) {
    console.error('⚠️  SESSION_ID import failed:', e.message)
    console.error('   First 16 chars received:', JSON.stringify(SESSION_ID.slice(0, 16)) + '…')
    console.error('   Falling back to pairing-code login.')
  }
}

// ── Session persistence in Supabase (Baileys custom auth state) ─────────────

export async function useSupabaseAuthState() {
  await importSessionString()

  let creds = await dbGet('creds')
  if (!creds) creds = initAuthCreds()

  return {
    state: {
      creds,
      keys: {
        get: async (type, ids) => {
          const data = {}
          await Promise.all(ids.map(async (id) => {
            const val = await dbGet(`${type}-${id}`)
            if (val) {
              if (type === 'app-state-sync-key') {
                data[id] = proto.Message.AppStateSyncKeyData.fromObject(val)
              } else {
                data[id] = val
              }
            }
          }))
          return data
        },
        set: async (data) => {
          await Promise.all(
            Object.entries(data).flatMap(([type, ids]) =>
              Object.entries(ids).map(([id, val]) =>
                val ? dbSet(`${type}-${id}`, val) : dbDel(`${type}-${id}`)
              )
            )
          )
        }
      }
    },
    saveCreds: async () => await dbSet('creds', creds)
  }
}

// ── Group helpers ─────────────────────────────────────────────────────────────

export async function registerGroup(groupId) {
  await sb.from('wa_group').upsert({ group_id: groupId })
}

export async function isGroupRegistered(groupId) {
  const { data } = await sb.from('wa_group').select('group_id').eq('group_id', groupId).single()
  return !!data
}

// ── Member helpers ────────────────────────────────────────────────────────────

export async function getMember(waId, groupId) {
  const { data } = await sb.from('wa_members').select('*').eq('wa_id', waId).eq('group_id', groupId).single()
  return data
}

export async function upsertMember(waId, groupId, username = '') {
  const existing = await getMember(waId, groupId)
  if (!existing) {
    await sb.from('wa_members').insert({ wa_id: waId, group_id: groupId, username, message_count: 0, level: 0, balance: 0 })
  } else if (username && existing.username !== username) {
    await sb.from('wa_members').update({ username }).eq('wa_id', waId).eq('group_id', groupId)
  }
}

export async function incrementMessages(waId, groupId) {
  const member = await getMember(waId, groupId)
  if (!member) return null
  const newCount  = (member.message_count || 0) + 1
  const newLevel  = Math.floor(newCount / 1000)
  const leveledUp = newLevel > (member.level || 0)
  const newBalance = leveledUp ? (member.balance || 0) + 10000 : (member.balance || 0)
  await sb.from('wa_members').update({
    message_count: newCount,
    level: newLevel,
    balance: newBalance
  }).eq('wa_id', waId).eq('group_id', groupId)
  return { leveledUp, newLevel, newBalance, newCount }
}

export async function getBalance(waId, groupId) {
  const member = await getMember(waId, groupId)
  return member ? (member.balance || 0) : 0
}

export async function updateBalance(waId, groupId, amount) {
  await sb.from('wa_members')
    .update({ balance: amount })
    .eq('wa_id', waId).eq('group_id', groupId)
}

export async function getTopMembers(groupId, limit = 10) {
  const { data } = await sb.from('wa_members')
    .select('wa_id, username, balance, level')
    .eq('group_id', groupId)
    .order('balance', { ascending: false })
    .limit(limit)
  return data || []
}

// ── Chat history ──────────────────────────────────────────────────────────────

export async function getChatHistory(waId) {
  const { data } = await sb.from('wa_chat_history').select('history').eq('wa_id', waId).single()
  return data ? data.history : []
}

export async function saveChatHistory(waId, history) {
  await sb.from('wa_chat_history').upsert({ wa_id: waId, history })
}
